model_size: conch_ViT-B-16

batch_size: 8
dataset: crc
data_path: /g/data/nk53/mr3328/wca/conch/CONCH/


alpha: 0.5
n_samples: 100
n_run: 1
patch_n: 30

# Patch extraction parameters
patch_scales: [0.25, 0.50, .75]          # Scales for multi-resolution patches
n_patches_per_scale: [5, 5, 5]        # Number of patches per scale

# Hybrid weighting parameters
hybrid_weight: 0.6                    # Weight for combining patch and global embeddings
sample_patches: true                 # Whether to sample a subset of patches
num_patches_to_sample: 30               # Number of patches to sample if sampling is enabled

# Class names for confusion matrix
class_names: ["Adipose", "Background", "Debris", "Lymphocytes", "Mucus", "Smooth muscle", "Normal colon mucosa", "Cancer-associated stroma", "Colorectal adenocarcinoma epithelium"] 

# Optional: Model path (if different from default)
# model_path: "/path/to/your/pretrained/model.bin"  # Uncomment and set if needed

methods:

  - cupl:
      name: cupl
      enabled: True
      prompts_file: "/g/data/nk53/mr3328/wca/conch/CONCH/prompts/crc/ours_filtered.json"