model_size: conch_ViT-B-16

batch_size: 16
dataset: bracs
data_path: /g/data/nk53/mr3328/bracs/binary/

alpha: 0.6
n_samples: 50
n_run: 1
patch_n: 10

methods:


  - clip:
      name: clip
      enabled: True
  - clip-e:
      name: clip-e
      enabled: True
  - clip-d:
      name: clip-d
      enabled: True
  - waffle:
      name: waffle
      enabled: True

  - ours:
      name: ours
      enabled: True
      image_scale: 4.0
      text_scale: 2.0
      prompts_file: "prompts/bracs/wca.json"