model_size: conch_ViT-B-16

batch_size: 16
dataset: ebhi
data_path: /g/data/nk53/mr3328/wca/WCA/ebhi/

alpha: 0.6
n_samples: 50
n_run: 1
patch_n: 10

methods:
  - clip:
      name: clip
      enabled: True
  - clip-e:
      name: clip-e
      enabled: True
  - clip-d:
      name: clip-d
      enabled: True
  - waffle:
      name: waffle
      enabled: True
  - cupl:
      name: cupl
      enabled: True
      prompts_file: "prompts/ebhi/cupl.json"
  - ours:
      name: ours
      enabled: True
      image_scale: 4.0
      text_scale: 2.0
      prompts_file: "prompts/ebhi/cupl.json"